FROM python:3.13.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir bandit safety

COPY . .

CMD ["sh", "-c", "\
    echo 'Security scan' && \
    bandit -r . -ll && \
    echo 'Vulnerability scan' && \
    safety check \
"]